### ISSUE TITLE
Make an iFramed Survey Component

### ISSUE THREAD

**Issue by kinggsagov** [GSA/GEAR3#346]

**Comment by hatfieldjm4** [comment]
@kinggsagov I created issue #347 which will likely supersede this issue because I met with the survey team, and the survey is a separate window that pops up. We would need to find an intuitive place on GEAR to place the survey link so that it stands out. I believe this issue can be closed, unless you'd like to discuss anything.

**Comment by kinggsagov** [comment]
Thanks. Closing it...
